

services:
  db:
    image: postgres:15-alpine
    container_name: smartexpense_db
    environment:
      POSTGRES_DB: smartexpense
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
